feat:
  - head-branch: ["^feat/", "^feature/"]

fix:
  - head-branch: ["^fix/", "^bugfix/", "^hotfix/"]

docs:
  - head-branch: ["^docs/"]
  - changed-files:
    - any-glob-to-any-file:
        - "*.md"
        - "docs/**"

ci:
  - head-branch: ["^ci/"]
  - changed-files:
    - any-glob-to-any-file:
        - ".github/**"

test:
  - head-branch: ["^test/", "^tests/"]
  - changed-files:
    - any-glob-to-any-file:
        - "tests/**"
        - "cypress/**"

chore:
  - head-branch: ["^chore/", "^deps/", "^dependabot/"]

refactor:
  - head-branch: ["^refactor/"]

perf:
  - head-branch: ["^perf/"]
