name: Install dependencies
description: Set up Node.js and install npm dependencies (caller must run actions/checkout first)

inputs:
  node-version:
    description: Node.js version to use
    default: '24.x'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      shell: bash
