name: Bug Report
description: Report a bug or unexpected behaviour
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug.
      placeholder: e.g. "Pokemon table does not load on first visit"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reliably trigger the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include screenshots or error output if relevant.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser / environment
      description: Browser name and version, OS, Node.js version (if running locally).
      placeholder: e.g. "Chrome 124, macOS 14, Node 22"
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low (cosmetic / minor inconvenience)
        - Medium (feature broken but workaround exists)
        - High (feature completely broken)
        - Critical (data loss / security issue)
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: I am using the latest commit on main.
          required: false
