name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe what you would like to see added or improved.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? What is the current limitation?
      placeholder: "I find it difficult to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you would like to happen. Be as specific as possible.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions or workarounds have you considered?
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application does this feature relate to?
      options:
        - Pokemon Table / List
        - Pokemon Detail View
        - Search / Filtering
        - Pagination
        - Performance
        - Accessibility
        - CI/CD / Tooling
        - Other
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: I am willing to submit a PR for this feature.
          required: false
